## external : influxdb

influxdb:
  enabled: true
  fullnameOverride: "cb-dragonfly-influxdb"
  database: "cbmon"
  adminUser:
    name: "cbmon"
    pwd: "password"
  persistence:
    enabled: false
    size: "8Gi"
    accessModes: "ReadWriteMany"


## external: kapacitor

kapacitor:
  enabled: true
  fullnameOverride: "cb-dragonfly-kapacitor"
  envVars:
    #KAPACITOR_INFLUXDB_0_URLS_0: http://cb-dragonfly-influxdb:8086
    KAPACITOR_INFLUXDB_0_USERNAME: cbmon
    KAPACITOR_INFLUXDB_0_PASSWORD: password
  persistence:
    enabled: false
    size: "8Gi"
    accessModes: "ReadWriteMany"
  influxURL: http://cb-dragonfly-influxdb:8086
  namespaceOverride: cloud-barista

## external : kafka

kafka:
  enabled: true
  replicas: 1
  fullnameOverride: "cb-dragonfly-kafka"
  external:
    enabled: true
    servicePort: 9092
    type: NodePort
  persistence:
    enabled: false
    size: "1Gi"
    accessModes: "ReadWriteMany"
  jmx:
    configMap:
      enabled: false
  prometheus:
    jmx:
      enabled: false
    kafka:
      enabled: false
    operator:
      enabled: false
    zookeeper:
      enabled: true
  configurationOverrides:
    KAFKA_ADVERTISED_LISTENERS: cb-dragonfly-kafka
    KAFKA_ZOOKEEPER_CONNECT: "cb-dragonfly-zookeeper:2181"
    KAFKA_DELETE_TOPIC_ENABLE: true
    KAFKA_LOG_RETENTION_MS: 10000
    KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
    KAFKA_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
    KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime

## external : zookeeper      

zookeeper:
  enabled: true
  exporters:
    fmx:
      enabled: false
  replicaCount: 1
  fullnameOverride: "cb-dragonfly-zookeeper"
  persistence:
    enabled: false
  exporters:
    jmx:
      enabled: false
  zookeeper:
    enabled: false
  prometheus:
    serviceMonitor:
      enabled: false
  env:
    ZOO_AUTOPURGE_SNAPRETAINCOUNT: 1


## cb-dragonfly custom variables
dragonfly:
  rootPath: "/go/src/github.com/cloud-barista/cb-dragonfly"

## chart values
replicaCount: 1

image:
  repository: cloudbaristaorg/cb-dragonfly
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "cb-dragonfly"

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  restPort: 9090
  grpcPort: 50254
  monitorPort: 8094

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cloud-barista.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m

nodeSelector: {}

tolerations: []

affinity: {}
